name: edtech
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_id: ^0.4.0
  bloc: ^8.1.4
  connectivity_plus: ^6.1.4
  decimal: ^3.0.2
  device_info_plus: ^10.1.0
  dio: ^5.8.0+1
  dropdown_search: ^6.0.2
  drop_down_list: ^2.0.0
  encrypt: ^5.0.3
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^3.0.1
  intl: ^0.19.0
  melos: ^6.3.2
  package_info_plus: ^8.3.0
  shared_preferences: ^2.2.2
  encrypted_shared_preferences: 3.0.1
  path_provider: 2.1.5
  async: 2.11.0
  dartx: 1.2.0
  flutter_bloc: 8.1.6
  flutter_screenutil: 5.9.3
  flutter_local_notifications: 18.0.1
  flutter_ringtone_player: 4.0.0+3

  firebase_analytics: 11.3.3
  firebase_core: 3.6.0
  firebase_crashlytics: 4.1.3
  firebase_messaging: 15.1.3
  firebase_remote_config: 5.1.3

  infinite_scroll_pagination: 4.0.0
  flutter_native_splash: ^2.4.4
  cupertino_icons: 1.0.8
  flutter_svg: 2.0.10+1
  go_router: 14.2.6
  injectable: 2.4.4
  get_it: 7.7.0
  rxdart: 0.28.0
  cached_network_image: 3.4.1
  lottie: 3.3.0
  json_annotation: 4.9.0
  url_launcher: 6.3.1
  shimmer: 3.0.0
  syncfusion_flutter_pdfviewer: 26.2.10
  photo_view: 0.15.0
  pinput: 4.0.0
  app_tracking_transparency: 2.0.5
  duration: ^4.0.3
  flutter_rating_bar: 4.0.1
  better_player_enhanced: 0.0.5
  carousel_slider: 5.0.0
  upgrader: 11.3.1
  table_calendar: 3.1.3
  simple_gesture_detector: 0.2.1
  sheet: 1.0.0
  appsflyer_sdk: 6.14.3
  htmltopdfwidgets: 1.0.6
  printing: ^5.13.2
  share_plus: ^10.0.2
  html_to_pdf: ^0.8.1
  meta: ^1.15.0
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.3.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  bloc_test: 9.1.7
  freezed: 2.4.6
  intl_utils: 2.8.7
  very_good_analysis: 6.0.0
  freezed_annotation: 2.4.1
  build_runner: 2.4.12
  custom_lint: 0.6.5
  flutter_gen_runner: 5.6.0
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  json_serializable: 6.8.0
  injectable_generator: 2.6.2
  mocktail: 1.0.4
  ant_lints:
    path: ./ant_lints

# flutter:
#   uses-material-design: true
#   generate: true
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/illustration/
    - assets/images/
    - assets/icons/
    - assets/jsons/
    - assets/images/logo_splash.png
    - assets/images/logo_foreground.png
    - assets/images/logo_background.png

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800

flutter_gen:
  output: lib/core/resource/generated
  line_length: 160
  null_safety: true

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true

flutter_intl:
  enabled: true
  main_locale: vi
  output_dir: lib/resources/generated
  arb_dir: lib/resources/l10n
